-- CREANDO TABLA
CREATE TABLE PERSONA01
( IDPERSONA INTEGER,
  PAT CHAR(50),
  MAT CHAR(50),
  NOM CHAR(50),
  DNI CHAR(8),
  ESTADO INTEGER ) TABLESPACE USERS;
  
DESCRIBE PERSONA01;  

SELECT * FROM PERSONA01;

-- CONSULTA ADMINISTRATIVA DE TABLAS
SELECT * FROM DBA_TABLES;

SELECT * FROM DBA_TABLES WHERE TABLE_NAME ='PERSONA01';

-- INSERTANDO DATOS EN PERSONA01
INSERT INTO PERSONA01 VALUES ( 1 , 'RIVERA' , 'SOLIS' , 'ELIAS' , '1111' , 1 );
INSERT INTO PERSONA01 VALUES ( 1 , 'KENT' , 'VELIZ' , 'ANA' , '1111' , 1 );
INSERT INTO PERSONA01 VALUES ( 2 , NULL , NULL , 'ELIAS' , '1111' , 1 );

SELECT * FROM PERSONA01;

-- CREANDO TABLA
CREATE TABLE PERSONA
( IDPERSONA INTEGER PRIMARY KEY, -- DATO UNICO Y NO NULO
  PAT CHAR(50)  NOT NULL,
  MAT CHAR(50)  NOT NULL,
  NOM CHAR(50)  NOT NULL,
  DNI CHAR(8) UNIQUE,
  FEC_NAC DATE,
  EDAD INTEGER CHECK ( EDAD >= 18),
  ESTADO INTEGER ) TABLESPACE USERS;
  
  CREATE TABLE AULA
  ( IDAULA INTEGER PRIMARY KEY,
    IDPERSONA INTEGER,
    IDCURSO INTEGER,
    ESTADO INTEGER);
  
  SELECT * FROM PERSONA;
  SELECT * FROM CURSO;
  SELECT * FROM AULA;
  
  --CREANDO FOREIGN KEY, VOY A MODIFICAR LA ATABLA AULA AGREGANDO UNA REGLA O CONSTRAINT
--1. FK AULA - PERSONA
ALTER TABLE AULA
ADD CONSTRAINT FK_AULA_PERSONA
FOREIGN KEY ( IDPERSONA)  REFERENCES PERSONA (IDPERSONA);

--2. FK AULA - CURSO
ALTER TABLE AULA
ADD CONSTRAINT FK_AULA_CURSO
FOREIGN KEY (IDCURSO) REFERENCES CURSO (IDCURSO);

-- INSERTAR DATOS EN TABLA CURSO
INSERT INTO CURSO VALUES ( 100,'ORACLE',400,1);
INSERT INTO CURSO VALUES ( 200,'SQL',400,1);
INSERT INTO CURSO VALUES ( 300,'PHP',300,1);
INSERT INTO CURSO VALUES ( 400,'CISCO',500,1);
COMMIT;
--INGRESANDO DATOS A TABLA AULA

INSERT INTO AULA VALUES ( 10, 2, 200, 1);

SELECT * FROM AULA;

INSERT INTO AULA VALUES ( 11, 20, 200, 1);  -- ERR PARA INCURRIR EN ERROR CODIGO PEONA NO EXISTE
INSERT INTO AULA VALUES ( 12, 3, 800, 1);  --ERR CON CODIGO DE CURSO QUE NO EXISTE
INSERT INTO AULA VALUES ( 13, 2, 400, 1); 
INSERT INTO AULA VALUES ( 14, 3, 400, 1);
INSERT INTO AULA VALUES ( 11, 1, 100, 1);
INSERT INTO AULA VALUES ( 12, 1, 200, 1);
INSERT INTO AULA VALUES ( 15, 1, 200, 1);





DESC PERSONA;


CREATE TABLESPACE TB_USERS


CREATE TABLE CURSO
( IDCURSO INTEGER PRIMARY KEY, -- DATO UNICO Y NO NULO
  NOMBRE CHAR(50)  NOT NULL,
  COSTO INTEGER CHECK ( COSTO >0),
  ESTADO INTEGER DEFAULT 1);


--COMPROBANDO CONSTRAINTS  O REGLAS
INSERT INTO PERSONA VALUES (1, 'RIVERA','SOLIS','ELIAS','1111','01/01/2000',18,1);
INSERT INTO PERSONA VALUES (1, 'RIVERA','SOLIS','ELIAS','2222','01/01/2000',18,1); -- ERROR ID
INSERT INTO PERSONA VALUES (2, 'RIVERA','SOLIS','ELIAS','222','01/01/2000',18,1);
INSERT INTO PERSONA VALUES (3, 'RIVERA','SOLIS','ELIAS','222','01/01/2000',18,1); -ERROR DNI
INSERT INTO PERSONA VALUES (3, 'RIVERA','SOLIS','ELIAS','333','01/01/2000',18,1);
INSERT INTO PERSONA VALUES (4, NULL,'SOLIS','ELIAS','222','01/01/2000',18,1); -- ERR NULO
INSERT INTO PERSONA VALUES (4, 'RIVERA','SOLIS','ELIAS','222','01/01/2000',8,1); --ERRO EDAD

SELECT * FROM PERSONA;

------TALLER 03

CREATE TABLE AFP (
       CODAFP               NUMBER(4) NOT NULL,
       DESCRIPCION          VARCHAR2(50) NULL,
       COMISION_FIJA        NUMBER(15,3) NULL,
       COMISION_VARIABLE    NUMBER(15,3) NULL,
       ESTADO               CHAR(1) NULL
);


ALTER TABLE AFP
       ADD  ( PRIMARY KEY (CODAFP) ) ;


CREATE TABLE AREA (
       CODAREA              NUMBER(4) NOT NULL,
       DESCRIPCION          VARCHAR2(40) NULL,
       ES_PRODUCCION        CHAR(1) NULL,
       ESTADO               CHAR(1) NULL
);


ALTER TABLE AREA
       ADD  ( PRIMARY KEY (CODAREA) ) ;


CREATE TABLE PLANILLA (
       CODPLANILLA          NUMBER NOT NULL,
       CODTRABAJADOR        NUMBER(4) NULL,
       ANNO                 NUMBER NULL,
       MES                  NUMBER NULL,
       BASICO               NUMBER(20,3) NULL,
       HRS_LAB              NUMBER(10,2) NULL,
       HRS_EXT              NUMBER(10,2) NULL,
       BASICO_CALCULADO     NUMBER(15,3) NULL,
       PAGO_HRS_EXTRAS      NUMBER(10,2) NULL,
       BONIFICACION         NUMBER(15,3) NULL,
       TOTAL_INGRESO        NUMBER(15,3) NULL,
       PRESTAMO             NUMBER(10,2) NULL,
       AFP_COMFIJA          NUMBER(20,2) NULL,
       AFP_COMVAR           NUMBER(15,2) NULL,
       FONDO                NUMBER(10,2) NULL,
       TOTAL_DSCTO          NUMBER(15,2) NULL,
       TOTAL_PAGO           NUMBER(10,2) NULL
);


ALTER TABLE PLANILLA
       ADD  ( PRIMARY KEY (CODPLANILLA) ) ;


CREATE TABLE PRESTAMOS (
       CODPRESTAMO          NUMBER(4) NOT NULL,
       CODTRABAJADOR        NUMBER(4) NULL,
       ANNO                 NUMBER NULL,
       MES                  NUMBER NULL,
       FECHA                DATE NULL,
       MONTO                NUMBER(15,3) NULL,
       ESTADO               CHAR(1) NULL
);


ALTER TABLE PRESTAMOS
       ADD  ( PRIMARY KEY (CODPRESTAMO) ) ;


CREATE TABLE REG_HRS_LABORADAS (
       CODREGHRS            NUMBER NOT NULL,
       CODTRABAJADOR        NUMBER(4) NOT NULL,
       NANNO                NUMBER NULL,
       NMES                 INTEGER NULL,
       HRS_LABORADAS        NUMBER(15,2) NULL,
       HRS_EXTRAS           NUMBER(15,3) NULL,
       ESTADO               CHAR(1) NULL
);


ALTER TABLE REG_HRS_LABORADAS
       ADD  ( PRIMARY KEY (CODREGHRS) ) ;


CREATE TABLE RPTBANCO (
       CODRPTBANCO          NUMBER NOT NULL,
       CODPLANILLA          NUMBER NULL,
       CODTRABAJADOR        NUMBER NULL,
       ANNO                 NUMBER NULL,
       MES                  NUMBER NULL,
       CTABANCO             VARCHAR2(20) NULL,
       DEPOSITO             NUMBER(10,2) NULL,
       ESTADO               VARCHAR2(1) NULL
);


ALTER TABLE RPTBANCO
       ADD  ( PRIMARY KEY (CODRPTBANCO) ) ;


CREATE TABLE TRABAJADORES (
       CODTRABAJADOR        NUMBER(4) NOT NULL,
       CODAFP               NUMBER(4) NULL,
       CODAREA              NUMBER(4) NULL,
       PATERNO              VARCHAR2(50) NULL,
       MATERNO              VARCHAR2(50) NULL,
       NOMBRE               VARCHAR2(50) NULL,
       TIPO                 VARCHAR2(1) NULL,
       CTABANCO             CHAR(20) NULL,
       BASICO               NUMBER(15,3) NULL,
       ESTADO               CHAR(1) NULL
);

ALTER TABLE TRABAJADORES
       ADD  ( PRIMARY KEY (CODTRABAJADOR) ) ;


----  GENERANDO RELACIONES
--1. FK RPTBANCO - PLANILLA
ALTER TABLE RPTBANCO
ADD CONSTRAINT FK_RPTBANCO_PLANILLA
FOREIGN KEY ( CODPLANILLA)  REFERENCES PLANILLA (CODPLANILLA);

--2. FK PLANILLA - TRABAJADORES
ALTER TABLE PLANILLA
ADD CONSTRAINT FK_PLANILLA_TRABAJADORES
FOREIGN KEY ( CODTRABAJADOR)  REFERENCES TRABAJADORES ( CODTRABAJADOR);

--3. FK PRESTAMOS - TRABAJADORES
ALTER TABLE PRESTAMOS
ADD CONSTRAINT FK_PRESTAMOS_TRABAJADORES
FOREIGN KEY ( CODTRABAJADOR)  REFERENCES TRABAJADORES ( CODTRABAJADOR);

--4. FK  TRABAJADORES - AREA
ALTER TABLE TRABAJADORES
ADD CONSTRAINT FK_TRABAJADORES_AREA
FOREIGN KEY ( CODAREA)  REFERENCES AREA ( CODAREA);

--5. FK  TRABAJADORES - AFP
ALTER TABLE TRABAJADORES
ADD CONSTRAINT FK_TRABAJADORES_AFP
FOREIGN KEY ( CODAFP)  REFERENCES AFP ( CODAFP);

--6. FK  REG_HRS_LABORADAS - TRABAJADORES
ALTER TABLE REG_HRS_LABORADAS
ADD CONSTRAINT FK_REG_HRS_LABORADAS_TRABAJADORES
FOREIGN KEY ( CODTRABAJADOR )  REFERENCES TRABAJADORES ( CODTRABAJADOR);

------TALLER LECCION 03 04  NOVEDADES

--------------------------------
-- 1. COLUMNAS INVISIBLES
--------------------------------
DROP TABLE EMPLEADO



 CREATE TABLE EMPLEADO
 ( IDEMPLEADO INTEGER ,
   PATERNO CHAR(50),
   MATERNO CHAR(50),
   NOMBRE CHAR(50),
   SALARY INTEGER INVISIBLE,
   ESTADO INTEGER );

SELECT * FROM EMPLEADO; 

DESC EMPLEADO;

ALTER TABLE EMPLEADO MODIFY SALARY VISIBLE;

SELECT * FROM EMPLEADO; 

ALTER TABLE EMPLEADO MODIFY SALARY INVISIBLE;

--------------------------------------------------
-- VALORES POR DEFECTO EN TABLA CON SECUENCIAS = GENERA CORRELATIVOS A LOS CAMPOS
--------------------------------------------------
CREATE SEQUENCE SQ_PRUEBA START WITH 100;

SELECT SQ_PRUEBA.NEXTVAL FROM DUAL; -- ASIGNA UNA SECUENCIA--------------------------------------------------

SELECT SQ_PRUEBA.CURRVAL FROM DUAL; -- ESTE ES EL VALOR ACTUAL

-- VALORES POR DEFECTO EN TABLA CON SECUENCIAS
--------------------------------------------------

CREATE SEQUENCE SQ_PROGRAMA;


CREATE TABLE PROGRAMA
( IDPROGRAMA INTEGER DEFAULT SQ_PROGRAMA.NEXTVAL,
  NOMBRE CHAR(100),
  ESTADO INTEGER DEFAULT 1 );
  
INSERT INTO PROGRAMA ( nombre, estado) VALUES ( 'ORACLE' , 1 );
INSERT INTO PROGRAMA ( nombre, estado) VALUES ( 'SQL' , 1 );
INSERT INTO PROGRAMA ( nombre, estado) VALUES ( 'PHP' , 1 );
SELECT * FROM PROGRAMA;



CREATE TABLE PROGRAMA
( IDPROGRAMA INTEGER DEFAULT SQ_CURSO.NEXTVAL,
  NOMBRE CHAR(100),
  ESTADO INTEGER DEFAULT 1 );
  
INSERT INTO PROGRAMA ( nombre, estado) VALUES ( 'ORACLE' , 1 );
INSERT INTO PROGRAMA ( nombre, estado) VALUES ( 'SQL' , 1 );
SELECT * FROM PROGRAMA;


