/*1*/
CREATE TABLESPACE TBS_AUTOS
  DATAFILE 'C:\PRACTICA\DF_AUTOS.DBF'
  SIZE 10M;

CREATE TABLESPACE TBS_CAMIONETAS
  DATAFILE 'C:\PRACTICA\DF_CAMIONETAS.DBF'
  SIZE 10M;
  
CREATE TABLESPACE TBS_BUSES
  DATAFILE 'C:\PRACTICA\DF_BUSES.DBF'
  SIZE 10M;
  
CREATE TABLESPACE TBS_CAMIONES
  DATAFILE 'C:\PRACTICA\DF_CAMIONES.DBF'
  SIZE 10M;
  

CREATE TABLE VEHICULOS(
ID NUMERIC(10),
TIPO VARCHAR(10),
AÑO INTEGER,
PLACA VARCHAR(10)
)
PARTITION BY LIST(TIPO)
(PARTITION vehiculos_AUTOS  VALUES('AUTOS')    tablespace TBS_AUTOS,
 PARTITION vehiculos_CAMIONETAS VALUES ('CAMIONETAS') tablespace TBS_CAMIONETAS,
 PARTITION vehiculos_BUSES     VALUES ('BUSES')     tablespace TBS_BUSES,
 PARTITION vehiculos_CAMIONES  VALUES('CAMIONES')   tablespace TBS_CAMIONES );
 
/*2*/
INSERT INTO VEHICULOS
SELECT LEVEL, 'AUTOS', '2017','PLACA'||LEVEL
FROM DUAL CONNECT BY LEVEL <= 15000;
/*3*/
INSERT INTO VEHICULOS
SELECT LEVEL, 'BUSES', '2017','PLACA'||LEVEL
FROM DUAL CONNECT BY LEVEL <= 25000;

/*4*/
SELECT * FROM VEHICULOS PARTITION ( vehiculos_AUTOS );

/*5*/
INSERT INTO VEHICULOS
SELECT LEVEL, 'MOTOS', '2017','PLACA'||LEVEL
FROM DUAL CONNECT BY LEVEL <= 5000;
  /*Rpta: Genera error debido a que no se creo una particion para el valor MOTOS en la tabla VEHICULOS*/
  
/*Consulta de todas las particiones*/
/*
SELECT * FROM VEHICULOS PARTITION ( vehiculos_AUTOS);
SELECT * FROM VEHICULOS PARTITION ( vehiculos_CAMIONETAS);
SELECT * FROM VEHICULOS PARTITION ( vehiculos_BUSES);
SELECT * FROM VEHICULOS PARTITION ( vehiculos_CAMIONES);
*/