 
 --PREGUNTA NUMERO 01
  CREATE TABLESPACE TBS_AUTOS
  DATAFILE 'C:\PRACTICA\DF_REGISTRO_AUTOS.DBF'
  SIZE 50M;
  
  CREATE TABLESPACE TBS_CAMIONETAS
  DATAFILE 'C:\PRACTICA\DF_REGISTRO_CAMIONETAS.DBF'
  SIZE 50M;
  
  CREATE TABLESPACE TBS_BUSES
  DATAFILE 'C:\PRACTICA\DF_REGISTRO_BUSES.DBF'
  SIZE 50M;
  
 CREATE TABLESPACE TBS_CAMIONES
  DATAFILE 'C:\PRACTICA\DF_REGISTRO_CAMIONES.DBF'
  SIZE 50M;
  
  SELECT * FROM DBA_TABLESPACES;
  
  
 CREATE TABLE VEHICULOS
(ID NUMBER(10),
 TIPO VARCHAR2(10),
 AÑO INTEGER,
 PLACA VARCHAR(10))
PARTITION BY LIST(TIPO)
(PARTITION VEHICULOS_AUTOS  VALUES('AUTO') tablespace TBS_AUTOS,
 PARTITION VEHICULOS_CAMIONETAS VALUES ('CAMIONETA') tablespace TBS_CAMIONETAS,
 PARTITION VEHICULOS_BUSES     VALUES ('BUS')     tablespace TBS_BUSES,
 PARTITION VEHICULOS_CAMIONES  VALUES('CAMION')   tablespace TBS_CAMIONES);

SELECT * FROM VEHICULOS;
--2 Insertar 15,000 AUTOS, verificar la partición donde se guarda dichos registros
INSERT INTO VEHICULOS
SELECT LEVEL, 'AUTO',2017,'PL_'||LEVEL
FROM DUAL CONNECT BY LEVEL < 15000;
--3Insertar 25,000 BUSES, verificar la partición donde se guarda dichos registros
INSERT INTO VEHICULOS
SELECT LEVEL, 'BUS',2017,'PL_'||LEVEL
FROM DUAL CONNECT BY LEVEL < 25000;
SELECT * FROM VENTAS;

--4. Utilizando SELECT PARTITION, liste los AUTOS.

SELECT * FROM VEHICULOS PARTITION ( VEHICULOS_AUTOS );
 
--5. Insertar 5,000 MOTOS. ¿Qué sucede?. Por que?
INSERT INTO VEHICULOS
SELECT LEVEL, 'MOTO',2017,'PL_'||LEVEL
FROM DUAL CONNECT BY LEVEL < 5000;

--NO SE PUEDE INSERTAR PORQUE DICHA PARTICION NO EXISTE

