
--    TALLER 02

  CREATE TABLESPACE TBS_REGPUBLICOS
  DATAFILE 'C:\TEMP\DF_REGPUBLICOS_01.DBF'
  SIZE 100M;


CREATE TABLE VEHICULOS
(ID NUMBER(10),
 TIPO VARCHAR(10),
 AÑO INTEGER,
 PLACA VARCHAR(10));


INSERT INTO VEHICULOS
SELECT LEVEL, 'AUTOS',2017, 'PL_' || LEVEL
FROM DUAL CONNECT BY LEVEL < 15000;


INSERT INTO VEHICULOS
SELECT LEVEL, 'BUSES',2017, 'PL_' || LEVEL
FROM DUAL CONNECT BY LEVEL < 25000;


SELECT * FROM VEHICULOS 
WHERE TIPO= 'AUTOS';

INSERT INTO VEHICULOS
SELECT LEVEL, 'MOTOS',2017, 'PL_' || LEVEL
FROM DUAL CONNECT BY LEVEL < 25000;
 