-- PREGUNTA 1
CREATE TABLESPACE TBS_AUTO
  DATAFILE 'C:\TEMP\DF_VEHICULO_AUTO.DBF'
  SIZE 100M;
  
  CREATE TABLESPACE TBS_CAMIONETA
  DATAFILE 'C:\TEMP\DF_VEHICULO_CAMIONETA.DBF'
  SIZE 100M;
  
  CREATE TABLESPACE TBS_BUS
  DATAFILE 'C:\TEMP\DF_VEHICULO_BUS.DBF'
  SIZE 100M;

  CREATE TABLESPACE TBS_CAMION
  DATAFILE 'C:\TEMP\DF_VEHICULO_CAMION.DBF'
  SIZE 100M;
  
 CREATE TABLE Vehiculo
(
  ID NUMERIC(10),
  Tipo VARCHAR(10),
  Anio INT,
  Placa VARCHAR(10)
)
PARTITION BY LIST( Tipo)
(PARTITION Vehiculo_Auto  VALUES('AUTO')    tablespace TBS_AUTO,
 PARTITION Vehiculo_Camioneta VALUES ('CAMIONETA') tablespace TBS_CAMIONETA,
 PARTITION Vehiculo_Bus     VALUES ('BUS')     tablespace TBS_BUS,
 PARTITION Vehiculo_Camion  VALUES('CAMION')   tablespace TBS_CAMION );

-- PREGUNTA 2
INSERT INTO Vehiculo(ID,TIPO,ANIO,PLACA)
SELECT LEVEL, 'AUTO', 2017,'XYZ'
FROM DUAL CONNECT BY LEVEL < 1000000;

-- PREGUNTA 3
INSERT INTO Vehiculo(ID,TIPO,ANIO,PLACA)
SELECT LEVEL, 'BUS', 2017,'XYZ'
FROM DUAL CONNECT BY LEVEL < 500000;

-- PREGUNTA 4

SELECT * FROM Vehiculo PARTITION ( Vehiculo_Auto );

-- PREGUNTA 5

 /*
INSERT INTO Vehiculo(ID,TIPO,ANIO,PLACA)
SELECT LEVEL, 'MOTOS', 2017,'MYZ'
FROM DUAL CONNECT BY LEVEL < 100000;
-- AL EJECUTAR LA CONSULTA SALE ERROR PORQUE NO HAY NINGUNA PARTICION PARA MOTOS
*/