
----------------------------------
-- PREGUNTA 1 
----------------------------------

  CREATE TABLESPACE TBS_AUTOS
  DATAFILE 'C:\TEMP\DF_AUTOS.DBF'
  SIZE 100M;
  
  CREATE TABLESPACE TBS_CAMIONETAS
  DATAFILE 'C:\PRACTICA\DF_CAMIONETAS.DBF'
  SIZE 10M;
  
  CREATE TABLESPACE TBS_BUSES
  DATAFILE 'C:\TEMP\DF_BUSES.DBF'
  SIZE 100M;
  
  CREATE TABLESPACE TBS_CAMIONES
  DATAFILE 'C:\PRACTICA\DF_CAMIONES.DBF'
  SIZE 10M;
  
  CREATE TABLE VEHICULOS
(ID NUMERIC(10),
TIPO VARCHAR(10),
 AÑO INTEGER,
 PLACA VARCHAR(10) )
PARTITION BY LIST( TIPO)
(PARTITION VEHICULOS_AUTOS  VALUES('AUTOS')    tablespace TBS_AUTOS,
PARTITION vehiculos_CAMIONETAS VALUES ('CAMIONETAS') tablespace TBS_CAMIONETAS,
PARTITION VEHICULOS_BUSES VALUES ('BUSES') tablespace TBS_BUSES,
PARTITION vehiculos_CAMIONES  VALUES('CAMIONES')   tablespace TBS_CAMIONES );
 
----------------------------------
-- PREGUNTA 2
----------------------------------
 INSERT INTO VEHICULOS
SELECT LEVEL, 'AUTOS','2017','PL_'||LEVEL
FROM DUAL CONNECT BY LEVEL <= 15000;

SELECT * FROM VEHICULOS PARTITION ( VEHICULOS_AUTOS );
----------------------------------
-- PREGUNTA 3
----------------------------------
 INSERT INTO VEHICULOS
SELECT LEVEL, 'BUSES','2017','PL_'||LEVEL
FROM DUAL CONNECT BY LEVEL <= 25000;

----------------------------------
-- PREGUNTA 4
----------------------------------
SELECT * FROM VEHICULOS PARTITION ( VEHICULOS_AUTOS );

----------------------------------
-- PREGUNTA 5 
----------------------------------
INSERT INTO VEHICULOS
SELECT LEVEL, 'MOTOS','2017','PL_'||LEVEL
FROM DUAL CONNECT BY LEVEL <= 5000;

-- ARROJA ERROR POR QUE EL DBF PARA EL TIPO DE VEHICULO MOTOS
  