----  GENERANDO RELACIONES
--1. FK RPTBANCO - PLANILLA
ALTER TABLE RPTBANCO
ADD CONSTRAINT FK_RPTBANCO_PLANILLA
FOREIGN KEY ( CODPLANILLA)  REFERENCES PLANILLA (CODPLANILLA);

--2. FK PLANILLA - TRABAJADORES
ALTER TABLE PLANILLA
ADD CONSTRAINT FK_PLANILLA_TRABAJADORES
FOREIGN KEY ( CODTRABAJADOR)  REFERENCES TRABAJADORES ( CODTRABAJADOR);

--3. FK PRESTAMOS - TRABAJADORES
ALTER TABLE PRESTAMOS
ADD CONSTRAINT FK_PRESTAMOS_TRABAJADORES
FOREIGN KEY ( CODTRABAJADOR)  REFERENCES TRABAJADORES ( CODTRABAJADOR);

--4. FK  TRABAJADORES - AREA
ALTER TABLE TRABAJADORES
ADD CONSTRAINT FK_TRABAJADORES_AREA
FOREIGN KEY ( CODAREA)  REFERENCES AREA ( CODAREA);

--5. FK  TRABAJADORES - AFP
ALTER TABLE TRABAJADORES
ADD CONSTRAINT FK_TRABAJADORES_AFP
FOREIGN KEY ( CODAFP)  REFERENCES AFP ( CODAFP);

--6. FK  REG_HRS_LABORADAS - TRABAJADORES
ALTER TABLE REG_HRS_LABORADAS
ADD CONSTRAINT FK_REG_HRS_LABORADAS_TRABAJADORES
FOREIGN KEY ( CODTRABAJADOR )  REFERENCES TRABAJADORES ( CODTRABAJADOR);
