ALTER TABLE RPTBANCO
ADD CONSTRAINT FK_RPTBANCO_PLANILLA
FOREIGN KEY(CODPLANILLA)
REFERENCES PLANILLA(CODPLANILLA);

ALTER TABLE PLANILLA
ADD CONSTRAINT FK_PLANILLA_TRABAJADOR
FOREIGN KEY(CODTRABAJADOR)
REFERENCES TRABAJADORES(CODTRABAJADOR);

ALTER TABLE REG_HRS_LABORADAS
ADD CONSTRAINT FK_HORAS_LAB_TRABAJADOR
FOREIGN KEY(CODTRABAJADOR)
REFERENCES TRABAJADORES(CODTRABAJADOR);

ALTER TABLE PRESTAMOS
ADD CONSTRAINT FK_PRESTAMOS_TRABAJADOR
FOREIGN KEY(CODTRABAJADOR)
REFERENCES TRABAJADORES(CODTRABAJADOR);

ALTER TABLE TRABAJADORES
ADD CONSTRAINT FK_TRABAJADOR_AREA
FOREIGN KEY(CODAREA)
REFERENCES AREA(CODAREA);

ALTER TABLE TRABAJADORES
ADD CONSTRAINT FK_TRABAJADOR_AFP
FOREIGN KEY(CODAFP)
REFERENCES AFP(CODAFP);
