-- PREGUNTA 1

CREATE TABLESPACE TBS_COMERCIAL
DATAFILE 'C:\PRACTICA\DF_COMERCIAL_01.DBF'
SIZE 15M;

CREATE TABLESPACE TBS_FINANZAS
DATAFILE 'C:\PRACTICA\DF_FINANZAS_01.DBF'
SIZE 10M;

ALTER TABLESPACE TBS_FINANZAS
ADD DATAFILE 'C:\PRACTICA\DF_FINANZAS_02.DBF'
SIZE 10M;

CREATE TABLESPACE TBS_CONTABILIDAD
DATAFILE 'C:\PRACTICA\DF_CONTABILIDAD.DBF'
SIZE 10M;

CREATE TABLESPACE TBS_LOGISTICA
DATAFILE 'C:\PRACTICA\DF_LOGISTICA_01.DBF'
SIZE 10M;

ALTER TABLESPACE TBS_FINANZAS
ADD DATAFILE 'C:\PRACTICA\DF_LOGISTICA_02.DBF'
SIZE 10M;

-- PREGUNTA 2

ALTER TABLESPACE TBS_CONTABILIDAD
ADD DATAFILE 'C:\PRACTICA\DF_CONTABILIDAD_02.DBF'
SIZE 15M;

--PREGUNTA 3

ALTER DATABASE 
DATAFILE 'C:\PRACTICA\DF_COMERCIAL_01.DBF'
RESIZE 25M;

-- PREGUNTA 4

CREATE TABLE PEDIDOS 
( ID NUMBER(10),
  FECHA DATE,
  REFERENCIA CHAR(100)  
  )
TABLESPACE TBS_LOGISTICA;

-- PREGUNTA 5
INSERT INTO PEDIDOS(ID,FECHA,REFERENCIA)
SELECT LEVEL ,CURRENT_DATE +(LEVEL-1), 'REFERENCIA' || LEVEL
FROM DUAL CONNECT BY LEVEL <= 10000;

-- pregunta 6 
DROP TABLESPACE TBS_CONTABILIDAD
INCLUDING CONTENTS AND DATAFILES;

-- PREGUNTA 7
ALTER TABLESPACE TBS_LOGISTICA OFFLINE;

-- PREGUNTA 8
ALTER TABLESPACE TBS_LOGISTICA ONLINE;
