---PRACTICA 01
--PREGUNTA 01 
--CREAR LOS SGTES TABLESPACES EN LA CARPETA C:\PRACTICA
--- CREANDO LOS TABLESPACE
CREATE TABLESPACE TB_COMERCIAL
DATAFILE 'C:\PRACTICA\DF_COMERCIAL_01.DBF'
SIZE 15M;

CREATE TABLESPACE TB_FINANZAS
DATAFILE 'C:\PRACTICA\DF_FINANZAS_01.DBF'
SIZE 10M;

ALTER TABLESPACE TB_FINANZAS
ADD DATAFILE 'C:\PRACTICA\DF_FINANZAS_02.DBF'
SIZE 10M;

CREATE TABLESPACE TB_CONTABILIDAD
DATAFILE 'C:\PRACTICA\DF_CONTABILIDAD.DBF'
SIZE 10M;

CREATE TABLESPACE TB_LOGISTICA
DATAFILE 'C:\PRACTICA\DF_LOGISTICA_01.DBF'
SIZE 10M;

ALTER TABLESPACE TB_LOGISTICA
ADD DATAFILE 'C:\PRACTICA\DF_LOGISTICA_02.DBF'
SIZE 10M;

--PREGUNTA 02
--AGREGAR UN NUEVO DATAFILE A TBS_CONTABILIDAD DE 15MB.
-- AMPLIANDO DATAFILE

ALTER TABLESPACE TB_CONTABILIDAD
ADD DATAFILE 'C:\PRACTICA\DF_CONTABILIDAD_02.DBF'
SIZE 15M;

--PREGUNTA 03
--AMPLIAR EL TAMAÑO DEL UNICO DATAFILE ASOCIADO AL TBS_COMERCIAL A 25MB.

ALTER DATABASE 
DATAFILE 'C:\PRACTICA\DF_COMERCIAL_01.DBF'
RESIZE 25M;

--PREGUNTA 04
--CREAR LA TABLA PEDIDOS EN TBS_LOGISTICA
--- CREACION DE LA TABLA EN TBS_LOGISTICA
CREATE TABLE PEDIDO 
( IDPEDIDO NUMBER (10),
  FECHA DATE,
  REFERENCIA CHAR(100))
TABLESPACE TB_LOGISTICA;

--PREGUNTA 05
--INSERTAR 10 MIL REGISTROS EN LA TABLA PEDIDOS, 
--VERIFIQUE EL PORCENTAJE DE POBLAMIENTO.
 INSERT INTO PEDIDO
 SELECT LEVEL, SYSDATE, 'REF_'||LEVEL
 FROM DUAL
 CONNECT BY LEVEL <=10000;
 
 SELECT /* + RULE */  df.tablespace_name "Tablespace",
       df.bytes / (1024 * 1024) "Size (MB)",
       SUM(fs.bytes) / (1024 * 1024) "Free (MB)",
       Nvl(Round(SUM(fs.bytes) * 100 / df.bytes),1) "% Free",
       Round((df.bytes - SUM(fs.bytes)) * 100 / df.bytes) "% Used"
  FROM dba_free_space fs,
       (SELECT tablespace_name,SUM(bytes) bytes
          FROM dba_data_files
         GROUP BY tablespace_name) df
 WHERE fs.tablespace_name (+)  = df.tablespace_name
 GROUP BY df.tablespace_name,df.bytes
UNION ALL
SELECT /* + RULE */ df.tablespace_name tspace,
       fs.bytes / (1024 * 1024),
       SUM(df.bytes_free) / (1024 * 1024),
       Nvl(Round((SUM(fs.bytes) - df.bytes_used) * 100 / fs.bytes), 1),
       Round((SUM(fs.bytes) - df.bytes_free) * 100 / fs.bytes)
  FROM dba_temp_files fs,
       (SELECT tablespace_name,bytes_free,bytes_used
          FROM v$temp_space_header
         GROUP BY tablespace_name,bytes_free,bytes_used) df
 WHERE fs.tablespace_name (+)  = df.tablespace_name
 GROUP BY df.tablespace_name,fs.bytes,df.bytes_free,df.bytes_used
 ORDER BY 4 DESC;
 
 --PREGUNTA 06
 --ELIMINAR EL TABLESPACE TBS_CONTABILIDAD. VERIFICAR.
 DROP TABLESPACE TB_CONTABILIDAD
 INCLUDING CONTENTS AND DATAFILES;

--PREGUNTA 07
--CAMBIAR EL ESTADO DEL TBS_LOGISITCA A OFFLINE, 
--CONSULTE LA TABLA PEDIDOS, QUE SUCEDE. PORQUE?

ALTER TABLESPACE TB_LOGISTICA OFFLINE;

 SELECT * FROM PEDIDO;
 
-- NO SE MUESTRA PORQUE SE DESACTIVO EL ESTADO 

--PREGUNTA 08
--MODIFICAR EL ESTADO DE TBS_LOGISTICA A ONLINE, CONSULTE LA TABLA PEDIDOS.

ALTER TABLESPACE TB_LOGISTICA  ONLINE;
SELECT * FROM PEDIDO;
   