CREATE TABLESPACE TBS_COMERCIAL
DATAFILE 'C:\PRACTICA\DF_COMERCIAL_01.DBF'
SIZE 15M;

CREATE TABLESPACE TBS_FINANZAS
DATAFILE 'C:\PRACTICA\DF_FINANZAS_02.DBF'
SIZE 10M;

ALTER TABLESPACE TBS_FINANZAS
ADD DATAFILE 'C:\PRACTICA\DF_FINANZAS_02.DBF'
SIZE 10M;

CREATE TABLESPACE TBS_CONTABILIDAD
DATAFILE 'C:\PRACTICA\DF_CONTABILIDAD.DBF'
SIZE 10M;

CREATE TABLESPACE TBS_LOGISTICA
DATAFILE 'C:\PRACTICA\DF_LOGISTICA_02.DBF'
SIZE 10M;

 ALTER TABLESPACE TBS_LOGISTICA
ADD DATAFILE 'C:\PRACTICA\DF_LOGISTICA_02.DBF'
SIZE 10M;

ALTER DATABASE 
DATAFILE 'C:\PRACTICA\DF_COMERCIAL_01.DBF'
RESIZE 25M;



2.	AGREGAR UN NUEVO DATAFILE A TBS_CONTABILIDAD DE 15MB.


ALTER TABLESPACE TBS_CONTABILIDAD
ADD DATAFILE 'C:\PRACTICA\DF_CONTABILIDAD_02.DBF'
SIZE 15M;



3.	AMPLIAR EL TAMAÑO DEL UNICO DATAFILE ASOCIADO AL TBS_COMERCIAL A 25MB.

ALTER DATABASE 
DATAFILE 'C:\PRACTICA\DF_COMERCIAL_01.DBF'
RESIZE 25M;

4----
CREATE TABLE PEDIDOS 
( ID NUMBER,
  ID_PEDIDO NUMBER(10),
  FECHA  DATE,
  REFERENCIA CHAR(100) )
TABLESPACE TBS_LOGISTICA;



5.	INSERTAR 10 MIL REGISTROS EN LA TABLA PEDIDOS, VERIFIQUE EL PORCENTAJE DE POBLAMIENTO.

INSERT INTO PEDIDOS
SELECT LEVEL,100,  SYSDATE,'REFERENCIA' || LEVEL
 FROM DUAL 
 CONNECT BY LEVEL <= 1000;

6.	ELIMINAR EL TABLESPACE TBS_CONTABILIDAD. VERIFICAR.
DROP TABLESPACE TBS_CONTABILIDAD
INCLUDING CONTENTS AND DATAFILES;

7.	CAMBIAR EL ESTADO DEL TBS_LOGISITCA A OFFLINE, CONSULTE LA TABLA PEDIDOS, QUE SUCEDE. PORQUE?
SELECT * fROM PEDIDOS;

ALTER TABLESPACE TBS_LOGISTICA OFFLINE;

SE LE PONE EN UN STANBY SOLO EL TABLESPACE
ALTER TABLESPACE TBS_LOGISTICA OFFLINE;
SE REAUNUDA EL FUNCIONAMIENTO DEL TABLESPACE


8.	MODIFICAR EL ESTADO DE TBS_LOGISTICA A ONLINE, CONSULTE LA TABLA PEDIDOS.

SELECT * fROM PEDIDOS;

ALTER TABLESPACE TBS_LOGISTICA ONLINE;
SE REAUNUDA EL FUNCIONAMIENTO DEL TABLESPACE




