-------------PRACTICA -------------
1
SELECT LAST_NAME , FIRST_NAME, SALARY 
FROM    EMPLOYEES;

2
SELECT LAST_NAME , FIRST_NAME, SALARY 
FROM    EMPLOYEES
WHERE   SALARY >=3000
ORDER BY 3 DESC;

3
SELECT EMPLOYEE_ID ID, FIRST_NAME || ' ' || LAST_NAME "DATOS EMPLEADOS" ,SALARY 
FROM    EMPLOYEES
WHERE COMMISSION_PCT IS NULL;

4

5
SELECT DISTINCT job_id
FROM   employees;

6
SELECT EMPLOYEE_ID ID, FIRST_NAME || ', ' || LAST_NAME || '-> ' ||job_id "EMPLEADOS Y PUESTOS" ,SALARY 
FROM    EMPLOYEES;


7
SELECT LAST_NAME EMPLEADOS , SALARY 
FROM    EMPLOYEES
WHERE  SALARY BETWEEN  13000 AND  17000 ;

8
SELECT  FIRST_NAME NOMBRE , LAST_NAME APELLIDO , JOB_ID PUESTO, SALARY
FROM    EMPLOYEES
WHERE SALARY >=2000 AND SALARY <= 3000  
OR     job_id LIKE '%SH_CLEARK%';

9