-- PREGUNTA N01

SELECT JOB_ID, FIRST_NAME || ' ' || LAST_NAME  "DATOS PERSONALES" , SALARY
FROM EMPLOYEES;


--PREGUNTA 02

SELECT FIRST_NAME || ' ' || LAST_NAME  "DATOS PERSONALES" , SALARY
FROM EMPLOYEES
WHERE SALARY >=3000
ORDER BY SALARY ASC ;


 --PREGUNTA 03
SELECT FIRST_NAME || ', ' || LAST_NAME  "DATOS DEL EMPLEADO" , SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT is null
order by SALARY ASC;

-- PREGUNTA 04

DESC EMPLOYEES;

--PREGUNTA 05
-- PREGUNTA 06
-- PREGUNTA 07
SELECT FIRST_NAME || ' ' || LAST_NAME  "DATOS PERSONALES" , SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN  13000 AND  17000
ORDER BY SALARY ASC ;

--PREGUNTA 08
SELECT  FIRST_NAME || ' ' || LAST_NAME  "DATOS PERSONALES" ,JOB_ID PUESTO, SALARY SUELDO
FROM EMPLOYEES
WHERE JOB_ID='SH_CLERK' AND
      SALARY BETWEEN  2000 AND  3000
ORDER BY SALARY ASC;
-- PREGUNTA 09
SELECT last_name, FIRST_NAME , HIRE_DATE, SALARY
FROM   employees
WHERE  hire_date BETWEEN '01/01/00' AND '31/01/00' 
ORDER BY SALARY ASC;
 