
----------------
--PREGUNTA 1
----------------
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEES;

----------------
--PREGUNTA 2
----------------
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEES
WHERE SALARY>=3000 ORDER BY SALARY DESC;

----------------
--PREGUNTA 3
----------------
SELECT EMPLOYEE_ID, FIRST_NAME || ' ' || LAST_NAME  "DATOS DE EMPLEADO",SALARY SUELDO,COMMISSION_PCT COMISION
FROM EMPLOYEES WHERE COMMISSION_PCT IS NULL ORDER BY SUELDO ASC ;


----------------
--PREGUNTA 4
----------------
--INGRESO A VER EN TODAS LAS TABLAS SELECCIONO LA TABLA REQUERIDA OPCION COLUMNAS



----------------
--PREGUNTA 5
----------------
SELECT DISTINCT JOB_ID FROM EMPLOYEES ;


----------------
--PREGUNTA 6
----------------
SELECT EMPLOYEE_ID "# ID", FIRST_NAME || ',' || LAST_NAME|| ' ' || '->'|| ' ' ||JOB_ID "EMPLEADOS Y PUESTOS"
FROM EMPLOYEES ;

----------------
--PREGUNTA 7
----------------

SELECT  FIRST_NAME || ',' || LAST_NAME EMPLEADOS,SALARY SUELDOS
FROM    EMPLOYEES 
WHERE  SALARY BETWEEN  13000 AND  17000 ;

----------------
--PREGUNTA 8
----------------

SELECT LAST_NAME APELLIDOS , FIRST_NAME NOMBRES ,JOB_ID PUESTO,SALARY SUELDO FROM EMPLOYEES
WHERE JOB_ID='SH_CLERK'AND SALARY BETWEEN  2000 AND  3000;


----------------
--PREGUNTA 9
----------------
SELECT LAST_NAME  , FIRST_NAME  ,HIRE_DATE,SALARY FROM EMPLOYEES
WHERE  HIRE_DATE BETWEEN  '01/01/2000' AND  '31/01/2000'
ORDER BY HIRE_DATE ASC;

----------------
--PREGUNTA 11
----------------
SELECT last_name
FROM   employees
WHERE  last_name LIKE '___a%' ;

----------------
--PREGUNTA 12
----------------
SELECT last_name,SALARY, job_id
FROM   employees
WHERE  job_id  IN ('SH_CLERK ', 'MK_REP ', 'HR_REP') ;


SELECT * FROM EMPLOYEES;