---TALLER
---1
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES;
--2
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES WHERE SALARY>=3000
ORDER BY SALARY DESC;
--3
SELECT EMPLOYEE_ID || ' ' || FIRST_NAME|| ' ' || LAST_NAME
"DATOS EMPLEADO", SALARY "SUELDO" FROM EMPLOYEES;

DESC EMPLOYEES;

SELECT DISTINCT JOB_ID FROM EMPLOYEES;

SELECT * FROM EMPLOYEES;
---6
SELECT EMPLOYEE_ID "ID",FIRST_NAME|| ' ' || LAST_NAME || '->' || JOB_ID
"EMPLEADOS Y PUESTOS" FROM EMPLOYEES;
--7
SELECT FIRST_NAME|| ' ' || LAST_NAME
"EMPLEADO", SALARY "SUELDOS"
FROM EMPLOYEES
WHERE SALARY BETWEEN 13000 AND 17000;
---8

SELECT LAST_NAME APELLIDOS,FIRST_NAME NOMBRES, JOB_ID PUESTO,
SALARY SUELDO
FROM EMPLOYEES
WHERE  salary BETWEEN 2000 AND 3000
AND    JOB_ID LIKE '%SH_C%' ;

---9
SELECT LAST_NAME,FIRST_NAME,HIRE_DATE,SALARY
FROM EMPLOYEES
WHERE  hire_date BETWEEN '01/01/2000' AND '31/01/2000'
ORDER BY HIRE_DATE ASC;
--11
SELECT LAST_NAME,SALARY 
FROM EMPLOYEES
WHERE LAST_NAME LIKE '____a%' ;
--12
SELECT LAST_NAME,SALARY, JOB_ID
FROM EMPLOYEES
WHERE JOB_ID IN ('SH_CLERK','MK_REP','HR_REP');