DESC EMPLOYEES;
--1
select EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEES;

--2
select EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEES 
WHERE SALARY >=3000 ORDER BY SALARY DESC;

--3
select EMPLOYEE_ID ID,FIRST_NAME|| ',' ||LAST_NAME "DATOS DE EMPLEADO",SALARY SUELDO,COMMISSION_PCT COMISION FROM EMPLOYEES 
WHERE COMMISSION_PCT IS NULL ORDER BY SALARY ASC;

--4 
DESC EMPLOYEES;

--5
select DISTINCT JOB_ID FROM EMPLOYEES ORDER BY 1;

--6
select EMPLOYEE_ID "# ID",FIRST_NAME|| ',' ||LAST_NAME|| '->' ||JOB_ID "EMPLEADO Y PUESTOS" FROM EMPLOYEES 
ORDER BY 2 ASC;

--7
select FIRST_NAME|| ',' ||LAST_NAME "EMPLEADOS",SALARY SUELDOS FROM EMPLOYEES 
WHERE SALARY BETWEEN 13000 AND 17000 ORDER BY 2 ASC;

--8
select LAST_NAME APELLIDOS,FIRST_NAME NOMBRES,JOB_ID PUESTO,SALARY SUELDO FROM EMPLOYEES 
WHERE JOB_ID ='SH_CLERK' AND SALARY BETWEEN 2000 AND 3000  ORDER BY 4 ASC;

--9
select LAST_NAME ,FIRST_NAME ,HIRE_DATE,SALARY  FROM EMPLOYEES 
WHERE HIRE_DATE BETWEEN '01/01/2000' AND '31/01/2000'  ORDER BY 3 ASC;

--11
select LAST_NAME ,SALARY  FROM EMPLOYEES 
WHERE LAST_NAME LIKE '___a%'  ORDER BY 1 ASC;

--12
select LAST_NAME ,SALARY,JOB_ID FROM EMPLOYEES 
WHERE JOB_ID in('SH_CLERK','MK_REP','HR_REP') ORDER BY 2 DESC;
