
-- PREGUNTA 1
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEES;

-- PREGUNTA 2
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEES
ORDER BY SALARY DESC;

-- PREGUNTA 3
SELECT FIRST_NAME || ','|| LAST_NAME "DATOS DE EMPLEADO",
SALARY SUELDO,COMMISSION_PCT COMISION FROM EMPLOYEES
WHERE COMMISSION_PCT IS NULL
ORDER BY SALARY ASC;

-- PREGUNTA 4
DESCRIBE EMPLOYEES;

-- PREGUNTA 5
SELECT DISTINCT JOB_ID FROM EMPLOYEES;

-- PREGUNTA 6
SELECT EMPLOYEE_ID "# ID",FIRST_NAME || ','|| LAST_NAME || '->' || JOB_ID "EMPLEADOS Y PUESTOS"
FROM EMPLOYEES;

-- PREGUNTA 7
SELECT EMPLOYEE_ID "# ID",FIRST_NAME || ','|| LAST_NAME "EMPLEADOS",SALARY SUELDOS
FROM EMPLOYEES
WHERE SALARY BETWEEN 13000 AND 17000;

--PREGUNTA 8
SELECT LAST_NAME APELLIDOS ,FIRST_NAME NOMBRES,JOB_ID PUESTO, SALARY SUELDO 
FROM EMPLOYEES
WHERE JOB_ID = 'SH_CLERK'
AND SALARY BETWEEN 2000 AND 3000;

-- PREGUNTA 9
SELECT LAST_NAME,FIRST_NAME,HIRE_DATE,SALARY 
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '01/01/2000' AND '31/01/2000' 
ORDER BY HIRE_DATE ASC;

-- PREGUNTA 10

-- PREGUNTA 11
SELECT LAST_NAME,SALARY 
FROM EMPLOYEES
WHERE LAST_NAME LIKE '___a%';

-- PREGUNTA 12
SELECT LAST_NAME,FIRST_NAME,JOB_ID
FROM EMPLOYEES
WHERE JOB_ID IN ('HR_REP','MK_REP','SH_CLERK');